### PR TITLE
Add kaufhaus layouts

### PR DESCRIPTION
**Pull request by SSirjes**
Closes: #123 

---

## Some guides for testing:
- [x]  Check if bgpicker, image drop area and page/article image saving works properly in the following layouts:
  - [x]  **Product list**
  - [x]  **Product**
- [x] Check if **Product list** layout works properly everywhere.
- [x] Check if **Product** layout works properly everywhere.
- [x] Check if **Blog & news** layout didn't broke down.
- [x] Check if **Product list** layout works up to second level in menu.
- [x] Check if **Product list** works for _root item_ (first page).
- [x] Check if **Product** works for _root item_ **(first page)**.
- [x] Check if main menu in desktop didn't broke down.
- [x] Check if main menu in mobile didn't broke down.
- [x] Do a small check for all other layouts to see if something got broken.
- [x] If **first page** is used as **Product list**, there's an option to hide _product_ related pages from main menu. Check if that works as intended.

### CODE REVIEW

**Comment by SSirjes** [comment]
* [ ] bind breadcrumbs menu color with design editor

**Comment by siimha** [comment]
Select field is missing select icon & borded in mobile view:
screen shot 2018-06-21 at 13 51 51 2

**Comment by siimha** [comment]
* [ ] If root_item layout is product list layout and you hide product & product list items from menu then it applies also to product layout when you change it to root_item. http://recordit.co/V7dVl5RX5K

**Comment by siimha** [comment]
* [ ] Menu separator is not visible if dark background:

screen shot 2018-06-21 at 15 42 16 2

**Comment by siimha** [comment]
* [ ] Remove --content-links-border-bottom from product & product list link

screen shot 2018-06-25 at 11 27 30 2

**Comment by SSirjes** [comment]
* [ ] Don't show link color under product box (preview mode)

**Comment by siimha** [comment]
* [ ] Border under product link (edit mode) & double border under product box & other links (preview mode) IE 11
toode

**Comment by siimha** [comment]
* [ ] IE 11 Double select icons in form field
select

**Comment by SSirjes** [comment]
* [ ] add active menu items styles.

**Comment by siimha** [comment]
content-item-box has bottom border in IE11 but doesn't in chrome (in preview mode when its a link)

screen shot 2018-07-10 at 14 26 09 2

**Comment by SSirjes** [comment]
* [ ] hide product related items in mobile menu (if they are hidden)

**Pull request merged**
